//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MerchantDataAccess
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;

    public partial class Logo
    {
        public System.Guid id { get; set; }
        [JsonIgnore]
        public System.Guid merchantid { get; set; }
        public Nullable<System.DateTime> date_created { get; set; }
        public int status { get; set; }
        public string path_to_file { get; set; }
        [JsonIgnore]
        public virtual Merchant Merchant { get; set; }
    }
}
